version: '3.2'

services:
 
  covid19-remote-work-api:
    image: bb.com.br/covid19-remote-work/api
    build: .
    restart: always
    network_mode: bridge
    links:
      - simple-file-server:simple-file-server
    ports:
      - 8000:8000
    environment: 
      - BASE_URL=http://localhost:8000
      - STORAGE_API_URL=http://simple-file-server:4000
      - CERTIFICATE_ISSUER_API_URL=http://domain.to.scep
      - USER_ROLED_API_URL=http://domain.to.ldap
      - CONDUCTOR_API_URL=http://conductor.to.ldap
  
  simple-file-server:
    image: flaviostutz/simple-file-server:1.0.1
    restart: always
    network_mode: bridge
    ports:
      - 4000:4000
    environment:
      - WRITE_SHARED_KEY=
      - READ_SHARED_KEY=
      - LOCATION_BASE_URL=http://localhost:4000
      - LOG_LEVEL=debug